SHELL    = /bin/sh
NAME     = all
MAKEFILE = Makefile

include $(GENIE)/src/make/Make.include

PACKAGE           = Flux
DICTIONARY        = _ROOT_DICT_Flux
LIBNAME           = libGFlux

all     : rootcint lib

include $(NUPROPEARTH)/src/make/Make.std-package-targets

FORCE: