SHELL    = /bin/sh
NAME     = all
MAKEFILE = Makefile

include $(GENIE)/src/make/Make.include

PACKAGE           = Driver
DICTIONARY        = _ROOT_DICT_Driver
LIBNAME           = libGDriver

all     : rootcint lib

include $(NUPROPEARTH)/src/make/Make.std-package-targets

FORCE: